### ISSUE TITLE
Blank and empty logic is inconsistent

### ISSUE THREAD

**Issue by jptissot** [sebastienros/fluid#304]
When updating our codebase to fluid 2.0, we found a bug with the blank and empty comparaisons.

We have an Orchard numeric field that can have a value between 0 and 20. 
In the code, we have logic that checks if the Field has a value and then outputs it.

```
{% assign myValue =  Model.ContentItem.Content.SomeType.SomeNumericField.Value %}
{% if myValue != empty %}
  this does not get displayed if myValue == 0
{% endif %}

{% if empty != myValue %}
  this gets displayed if myValue == 0
{% endif %}
```

I think this is because in the first case, myValue's type is used in the comparaison and `empty` is transformed to a number (with value of 0) and then the comparaison is made `0 = 0`. In the second case, `empty` litteral type Equals() method is used and the logic works.

**Comment by sebastienros** [comment]
I recently ran a lot of tests in Shopify directly to ensure it's right:  https://github.com/sebastienros/fluid/blob/main/Fluid.Tests/ParserTests.cs#L531

But I haven't tried with other types than text. Will do. Can the C# value be null? Are you checking for that with empty? 
In that case you could try `blank` because `nil == empty` is false, but `nil == blank` is true.

**Comment by sebastienros** [comment]
Can you explain what you are trying to check? If the value has a value as in "not null" ?

**Comment by jptissot** [comment]
Yes, and we want to output when it's 0

**Comment by sebastienros** [comment]
a == 0 or a == blank

This is what u would write but I will have to test that

**Comment by sebastienros** [comment]
I understand the discrepancy, fixing
