### ISSUE TITLE
Comparision between string and number went broken

### ISSUE THREAD

**Issue by MLevein** [sebastienros/fluid#313]
When I updated from 1.0.0-beta-9571 to 2.0.5 the comparision "1" == 1 stopped being true (which my scripts assume it to be).

 ```
        private static readonly FluidParser _fluidParser = new FluidParser();

        [Test]
        public void ComparisionStringInt()
        {
            string numberOne = "1";

            var context = new TemplateContext();
            context.Options.MemberAccessStrategy.Register(numberOne.GetType());
            context.SetValue("foo", numberOne);

            var template = _fluidParser.Parse("{% if foo == 1 %}true{% else %}false{% endif %}");
            var output = template.Render(context, System.Text.Encodings.Web.HtmlEncoder.Default);
            Assert.AreEqual(output, "true");
        }
 ```

**Comment by lahma** [comment]
I think it's because 2.0 works more like the specification states, [see example in the playground](https://liquidjs.com/playground.html#eyUgYXNzaWduIG51bSA9ICIxIiAtJX0KeyUgaWYgbnVtID09IDEgICAlfWlzIG51bWJlcnslIGVuZGlmIC0lfQp7JSBpZiBudW0gPT0gJzEnICV9aXMgc3RyaW5neyUgZW5kaWYgLSV9Cgo=).

**Comment by MLevein** [comment]
Might be. Than I would suggest a "jsTruthy"-option (like liquidjs has), to be able to switch back to type-agnostic comparision in if- and case-operations and alike.

**Comment by lahma** [comment]
By the looks of it, this requires some API changes like `ToBooleanValue` accepting options to figure out how to interpret the value.

**Comment by sebastienros** [comment]
I don't think it's related to ToBooleanValue, more to the evaluation of the equality statement when comparing heterogenous types.
I also don't think it's related to thuthyness (https://liquidjs.com/tutorials/truthy-and-falsy.html#Use-JavaScript-Truthy) because for the same reason, it's not related to `ToBooleanValue`.

**Comment by lahma** [comment]
What about `if ("1")`, there's no comparison but should be true in JS I guess? What I understand the `ToBooleanValue` is the way comparisons are made when checking for truthiness.

**Comment by sebastienros** [comment]
Sure, but that is not the issue here.

**Comment by sebastienros** [comment]
And in the case of liquidjs they support am option to use the same thruthiness as javascript, just because it's a js framework

**Comment by MLevein** [comment]
Maybe I misunderstood the meaning of liquidjs's jsTruthy option. But as @sebastienros correctly understands, my suggestion is an option to switch back to type-independent comparitions (like javascript has, where 1=="1" is true, but 1==="1" is false).

**Comment by sebastienros** [comment]
I won't provide such option, this is counter to the spec, and I don't see any real usage of this, since you can already force the conversion to a string or a number by yourself if you want to be explicit about how to convert the values. There is also another extensibility point since you can define custom binary operators that would do whatever you want, like a new "same" operator for instance.

**Comment by drosenba** [comment]
I see that this is an old/closed issue, but I'd like to discuss it further if you don't mind, because I see that one of these does evaluate 'true'

{% if "1" == 1 %}
"1" == 1
{% endif %}

{% if 1 == "1" %}
1 == "1"
{% endif %}

The output  is
1 == "1"


Would you please point me to the "spec" you refer to?  I've searched the docs at shopify.dev, and I don't see any mention of **how** equality should deal with heterogeneous types.

Would you please expand on " you can already force the conversion to a string or a number", because it seems to me that one could only do that in "custom binary operators", because you would need to know what the other operator's type is too.  I.e., it's not safe to convert everything to a string, since, for example, "<" would fail for:  "9" < 10  .  And similarly, it's not safe to TryParse convert numbers to strings, because the other operator may be a string too (i.e., two strings should compare as strings).
