### ISSUE TITLE
Bug/new behavior of whitespace control from 2.x cause can't detect filter

### ISSUE THREAD

**Issue by tangkhaiphuong** [sebastienros/fluid#347]
From Fluid 1.0. I wrote the code below

```csharp
  var fluidTemplate = FluidTemplate.Parse("{%-assign len = \"1,2,3\" |  split: \",\" | size-%}{{len}}");
  Console.WriteLine(fluidTemplate.Render(new TemplateContext())); // Output: 3
```

Then I upgrade to Fluid 2.0.12

```csharp
var fluidTemplate = new FluidParser().Parse("{%-assign len = \"1,2,3\" | split: \",\" | size-%}{{len}}");
Console.WriteLine(fluidTemplate.Render(new TemplateContext())); // Output: 123
```

To workaround this case (I want output : 3) I need put the whitespace in `size-%}{{len}}");` become `size -%}{{len}}");`

**Comment by sebastienros** [comment]
I can repro the issue. Will fix asap.

**Comment by sebastienros** [comment]
Interestingly, the issue is that `size-` is a valid identifier, so it's trying to find a filter with this name, while in this case the `-` is part of `-%}`. This is ambiguous as both are valid syntaxes, but still I agree that for this case the `-` should not be expected to be the end of a filter name.

**Comment by tangkhaiphuong** [comment]
@sebastienros Can you publish this fix on nuget?
