### ISSUE TITLE
Problem with converting double/float values

### ISSUE THREAD

**Issue by as94dodo** [sebastienros/fluid#378]
I got overflow exception when i converting too small/too high double value. I already fixed that and want to create PR, but i haven't permission on it. Please, give me permission on pushing new branch for solving this problem.

**Comment by Soar360** [comment]
You can fork this repository to your owner account and create a pull request .

**Comment by Soar360** [comment]
You can fork this repository to your owner account and create a pull request .

**Comment by sebastienros** [comment]
Not sure what should be the behavior in this case. Your PR is preventing the exception, but it's sneaky since now you could see a wrong value. Not sure it's even better. I could just file an issue saying that the rendered value is wrong! It's also kind of scary, let's say what you are displaying in bounding to your customers, you might render something totally wrong.

The solution might be to detect the problem like you are doing, but throw a Fluid specific exception that can be caught by the caller to display an error message and log the issue somewhere. We should check what other template engine do in these situations.

**Comment by hishamco** [comment]
@as94dodo regarding your case I'm not sure if there's an extensibility point to do such thing, what I knew is `FluidValue` one of the core classes that many APIs depend on
