### ISSUE TITLE
Time conversion problem

### ISSUE THREAD

**Issue by huangyedie** [sebastienros/fluid#541]
var source = "date:\"{{Date | date:'%F %T.%3N'}}\"";

![image](https://user-images.githubusercontent.com/51399090/208361058-0d0783a2-af19-4a49-a58d-37fcfe40e1bf.png)

%3N does not take effect , 是什么问题呢？

Of course, use format_ Date is OK
| format_date:'yyyy-MM-ddTHH:mm:ss.fffZ'

**Comment by hishamco** [comment]
Could you please try before [this ](https://github.com/sebastienros/fluid/commit/934e3958359c5b3a035e6c25392662d6a25518de) commit?

**Comment by nicholas-brooks** [comment]
If I can chime in (I was busy doing some other datetime work):

@hishamco - Does not look like %N is handled - I can't see a test case at:
https://github.com/sebastienros/fluid/blob/a6393d43f26c4a2318d1e56fa9646e0f477b2a24/Fluid.Tests/MiscFiltersTests.cs#L255

and `case 'N'` doesn't appear to be handled by MiscFilters.Date: https://github.com/sebastienros/fluid/blob/a6393d43f26c4a2318d1e56fa9646e0f477b2a24/Fluid/Filters/MiscFilters.cs#L297

@huangyedie - You could use %L instead of %3N as a work around.

**Comment by hishamco** [comment]
You are right, I looked though the code it wasn't handled
