### ISSUE TITLE
Incorrect position in validation messages

### ISSUE THREAD

**Issue by gluhovds** [sebastienros/fluid#69]
When parsing the following block of code:

```
<div>
	<span>
		{{{ model }}
	</span>
</div>
```

I'm getting an error: `Invalid character: '{'. at line:0, col:2`

This is a little unclear, since the error actually occurred in line 2. It looks like the parser returns character position in this particular Liquid expression, but not in the whole template.

It would be great to track the original position.

**Comment by hishamco** [comment]
@gluhovds basically this is coming from `Irony`
/cc @sebastienros

**Comment by sebastienros** [comment]
The issue is that I must be extracting these tags out of their context, and then invalidate the position. The solution might be to intercept the exception, then alter the position based on the metadata containing the original line/column offset in the source document.

**Comment by jeremycook** [comment]
@sebastienros @hishamco I'm interested in looking into this problem. What file(s) should I be looking at as a starting place?

**Comment by hishamco** [comment]
As I mentioned earlier this came from `Irony` but seems @sebastienros idea to intercept the exception and dig into that to extract the original line & column

**Comment by sebastienros** [comment]
Yeah, look at the exception first, and see what is available, probably the delta to apply is available somewhere ... if it's not the case then it would have to be added once the different tags are parsed. The issue is that I am first extracting the tags manually, then parsing each of them using irony. And when I parse them they somehow all start at (0,0). So maybe have a parameter on the parsing for pass in the delta which will be added to each token's location when one is found.
